### ISSUE TITLE
What's the cache location?

### ISSUE THREAD

**Issue by BalestraPatrick** [capitalone/SWHttpTrafficRecorder#1]
Hello,

I'm using the project in my app and I'm trying to record my traffic on the Simulator. I added this line in my `didFinishLaunchingWithOptions` method: `SWHttpTrafficRecorder.sharedRecorder().startRecording()`

I've tried looking in my app's directory but I could't find any data in the cache directory (which I think is the default one). Could you please help?

Thanks a lot.

**Comment by JinlianWang** [comment]
Are you using NSURLSession for your networking, if so, you may need to use `- (BOOL)startRecordingAtPath:(NSString *)recordingPath forSessionConfiguration:(NSURLSessionConfiguration *)sessionConfig error:(NSError **) error` instead. 

The cache location for Simulator is something like `/Users/[user name]/Library/Developer/CoreSimulator/Devices/[device serial number like, A55973FB-43D8-498E-84F5-5C31F05028A5]/data/Containers/Data/Application/[application serial number, like 2FFFAF10-47C9-41F0-8057-C14EC364A92E]/Library/Caches/`. 

If you check out the demo project, it implements the progress delegate which can tell you whenever a request/response is recorded.

**Comment by JinlianWang** [comment]
@BalestraPatrick let me know if you still run into the same problem.

**Comment by BalestraPatrick** [comment]
I'm using Alamofire. Should I still use that method you described?

**Comment by JinlianWang** [comment]
Not used Alamofire before. Though it seems to use NSURLSession and yes, you may want to use the other method for session configuration instead. Check out `Alamofire.Manager.sharedInstance.session.configuration`.

**Comment by BalestraPatrick** [comment]
Cool, thanks and sorry for the delay. I don't see any JSON file but I only see some `.binarycookies` and `.tail` files. My recording format is set to `Mocktail`. 
Thanks!

**Comment by JinlianWang** [comment]
Awesome. So it is working as expected? If you want JSON, you need to set the recording format to SWHTTPTrafficRecordingFormatBodyOnly.

**Comment by JinlianWang** [comment]
@BalestraPatrick Has the answer solved your problem? I am about to close the issue but want to check with you first.

**Comment by BalestraPatrick** [comment]
Unfortunately I wasn't able to generate a JSON file but I changed approach. Thanks for the help!

**Comment by johndpope-karhoo** [comment]
Should add the sample code to readme.md

```

  #ifdef DEBUG
    [SWHttpTrafficRecorder sharedRecorder].recordingFormat =  SWHTTPTrafficRecordingFormatBodyOnly;
    NSArray *documentPath = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES);
    NSString *docs = [documentPath objectAtIndex:0];
    NSString *path = [docs stringByAppendingPathComponent:@"yourdirectory"];

    [[SWHttpTrafficRecorder sharedRecorder] startRecordingAtPath:path error:nil];

    #endif
```
