### ISSUE TITLE
Publish a new release with Carthage support

### ISSUE THREAD

**Issue by sccheng** [capitalone/SWHttpTrafficRecorder#11]
Hi!

Looks like the latest release is version 1.0.1, which was released before Carthage support was added - so doing a Carthage update results in this error:

`*** Skipped building SWHttpTrafficRecorder due to the error:
Dependency "SWHttpTrafficRecorder" has no shared framework schemes`

A workaround is to specify the master branch in the Cartfile, instead of a version: 
`github "capitalone/SWHttpTrafficRecorder" "master"`,
but it would be great if there were a stable release including Carthage support.

**Comment by JinlianWang** [comment]
@sccheng I just published a new release 1.0.2 with latest code. I am not using Carthage, so could you verify everything is working fine for you, especially the Carthage? Thanks a lot!

**Comment by sccheng** [comment]
Hey @JinlianWang, seems like I'm still pulling Carthage is still pulling version 1.0.1. On the releases page, v1.0.1 is still marked as the latest release. I think you may have to manually publish a release in addition to pushing the 1.0.2 tag?

**Comment by JinlianWang** [comment]
@sccheng Just create a release of 1.0.2 manually. Does it work for you now?

**Comment by sccheng** [comment]
Hi @JinlianWang, right now I'm getting this error from Carthage:

```
*** Checking out SWHttpTrafficRecorder at "1.01"
*** Skipped building SWHttpTrafficRecorder due to the error:
Dependency "SWHttpTrafficRecorder" has no shared framework schemes
```

I talked to my coworker, and we have a theory. Carthage should pull down the latest version, if we don't specify a version in the Cartfile. It's possible that the "1.01" tag you have is seen as a later version than the 1.0.2 release (1.01 = 1.1), so Carthage grabs the wrong version of the repo.

We think that the issue will probably be fixed if you either delete the 1.01 tag or release a 1.1 version with Carthage support!

**Comment by JinlianWang** [comment]
@sccheng Sorry, what a typo I made. Just correct 1.01 to 1.0.1. Thanks for help out!

**Comment by sccheng** [comment]
Great!! It seems to be working now! Thanks for the quick replies and fixes!

**Comment by JinlianWang** [comment]
@sccheng Thanks a lot for the help!!! I am closing this issue.
