### ISSUE TITLE
Can't import in Swift project after installing through CocoaPods

### ISSUE THREAD

**Issue by irodrigo17** [capitalone/SWHttpTrafficRecorder#2]
I installed SWHttpTrafficRecorder through CocoaPods in a Swift project, then tried to import it in the `AppDelegate` with `import SWHttpTrafficRecorder` but I get a _No such module.._ error. I think the pod is missing the bridging header file.

**Comment by JinlianWang** [comment]
Not an expert over CocoaPods.  Have you found a solution? Feel free to make a pull request if so. Or I may take some time later to see what I can do.

**Comment by irodrigo17** [comment]
Thanks for the quick reply. 
I'll try to come up with a pull request later today.

**Comment by tspop** [comment]
Just import the library in your bridging header
`#import <SWHttpTrafficRecorder/SWHttpTrafficRecorder.h>`

**Comment by JinlianWang** [comment]
@irodrigo17 I did get some time and give it a try today and it works for me. Have you included 'use_frameworks!' in your podfile? Once you did that, you need to build the project so that the dependent frameworks are ready, before importing them. let me know whether it fixes your problem.

**Comment by irodrigo17** [comment]
Thanks! I think there was an issue with my project setup, haven’t tried again, but I’ll let you know when I do.

**Comment by JinlianWang** [comment]
@irodrigo17 I am closing this issue if this works for you now?
